### ISSUE TITLE
麻烦您更新one-nba.enc，新赛季了

### ISSUE THREAD

**Issue by Hpxwd** [Nicolasking007/Scriptable#11]

**Comment by Nicolasking007** [comment]
找个时间  我看一下

**Comment by Nicolasking007** [comment]
已修复并上传，请自行更新即可

**Comment by Hpxwd** [comment]
您好，似乎在ios15上显示不正常，ios16正常
![7FAD1E5C-2E19-4E15-81D3-926644CF7A13](https://user-images.githubusercontent.com/113987466/200735427-0555aea7-e559-48f7-8e35-97f4725e2dc5.jpeg)
![7F7C028F-4EC4-489B-9FB5-B0D2C1287657](https://user-images.githubusercontent.com/113987466/200735431-8024e18d-e4e4-4926-b1e0-ccac42ae6716.jpeg)
