### ISSUE TITLE
您好，one.nba组件我已经设置好了固定的背景，然而每次运行或者更换球队会再次出现配置背景弹窗，能否在已设置固定背景的前提下省掉配置背景弹窗，谢谢

### ISSUE THREAD

**Issue by Hpxwd** [Nicolasking007/Scriptable#13]

**Comment by Nicolasking007** [comment]
再改回false 即可

**Comment by Hpxwd** [comment]
谢谢解答

**Comment by Hpxwd** [comment]
> 再改回false 即可

您好，未来赛程似乎比现实提早了一天😭
![4FC6C33B-19CD-4FF4-B225-35FE0110E5AA](https://user-images.githubusercontent.com/113987466/200748365-6ef41edf-7f8b-4b4f-838e-3e562311be4d.png)
![5FEFE969-8400-414D-98C1-B497E9E8C8BC](https://user-images.githubusercontent.com/113987466/200748376-579fc1b6-6be1-429e-be1b-cc64985c3f33.png)

**Comment by Nicolasking007** [comment]
已修复
