### ISSUE TITLE
ONE-NBA.Enc.js 无法展示实时比分。

### ISSUE THREAD

**Issue by wilsonxu7** [Nicolasking007/Scriptable#19]
无法展示当前进行中比赛的实时比分，组件直接展示了下一场比赛。

**Comment by wilsonxu7** [comment]
solve: 904行的时间换算，要换算成gdte时间。如果使用北京时间，则需要减去14小时。
调整后为：
`dStartDate.setHours(dStartDate.getHours() -14);`

**Comment by Nicolasking007** [comment]
感谢反馈

**Comment by wilsonxu7** [comment]
又重新捋了一下，原先的-6小时，是没错的。-6小时是换算到美国的东部时间，

但是
`new Date(dDate.toDateString()) >= new Date(dStartDate.toDateString())`
这里进行比对的时候，是拿比赛的开始时间去和换算后的美国东部时间比较。比赛一旦开始，那么当前比赛就不符合这个 >= 的条件，因此不会返回。

根据nba一场比赛2-3小时，背靠背比赛也是隔天，因此换算时间，在-6的基础上再 -3 小时以上即可。

当然-14小时也不会影响返回。只会让今天的比赛完赛后，比分在组件中继续展示n小时。
