### ISSUE TITLE
订阅脚本存在路径拼写大小写错误，望修复

### ISSUE THREAD

**Issue by xunichanghuan** [Nicolasking007/Scriptable#5]
如
https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-tool/ONE-Tool.Enc.js
拼写成
https://raw.githubusercontent.com/Nicolasking007/Scriptable/main/ONE-Tool/ONE-Tool.Enc.js
最终导致订阅无法更新

**Comment by Nicolasking007** [comment]
OK 我周末 调整一下 感谢反馈
