### ISSUE TITLE
希望添加收录 ChinaTelecomPanel

### ISSUE THREAD

**Issue by LambdaExpression** [Nicolasking007/Scriptable#8]
https://lambdaexpression.github.io/ScriptablesComponent/ChinaTelecomPanel/

这是一个中国电信面板插件。配合 [ChinaTelecomMonitor](https://github.com/LambdaExpression/ChinaTelecomMonitor) 使用无须再反复手动获取登录cookie

这个是我写的一个的小插件，主要希望能解决电信cookie容易失效问题。看见贵项目收集了挺多脚本，希望我的这个小插件也能被收录到其中

**Comment by Nicolasking007** [comment]
已收录
